// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJlPfAfA7eSih9o2fcZ9H2eWIX97OmxVE',
    appId: '1:233919688520:web:640d842a88d1f925c14d7d',
    messagingSenderId: '233919688520',
    projectId: 'fir-flutter-codelab-23eb1',
    authDomain: 'fir-flutter-codelab-23eb1.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-23eb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb5SbyX8EpAVxHkd83tOMmdkUqQRwcg-U',
    appId: '1:233919688520:android:3e2d932d241556fac14d7d',
    messagingSenderId: '233919688520',
    projectId: 'fir-flutter-codelab-23eb1',
    storageBucket: 'fir-flutter-codelab-23eb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5TCGcjY6r71BxMLdenN8z-rz6W5Tg-OE',
    appId: '1:233919688520:ios:3ba1a0400e0d14a0c14d7d',
    messagingSenderId: '233919688520',
    projectId: 'fir-flutter-codelab-23eb1',
    storageBucket: 'fir-flutter-codelab-23eb1.appspot.com',
    iosClientId: '233919688520-f8rvrm5oa4mm462k13bq11fu1j1c3iot.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5TCGcjY6r71BxMLdenN8z-rz6W5Tg-OE',
    appId: '1:233919688520:ios:3ba1a0400e0d14a0c14d7d',
    messagingSenderId: '233919688520',
    projectId: 'fir-flutter-codelab-23eb1',
    storageBucket: 'fir-flutter-codelab-23eb1.appspot.com',
    iosClientId: '233919688520-f8rvrm5oa4mm462k13bq11fu1j1c3iot.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
